# Generated by Django 4.1.2 on 2023-05-01 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NUMERO_CUENTA', models.CharField(max_length=100)),
                ('VALOR_CUENTA', models.CharField(max_length=20)),
                ('FECHA_CREACION', models.DateTimeField(auto_now_add=True)),
                ('ESTADO', models.CharField(default=None, max_length=20)),
                ('USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
