# Generated by Django 4.1.2 on 2023-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='VALOR_CUENTA',
            field=models.IntegerField(),
        ),
    ]
